chore(deps): bring in an explicit version of jackson-databind
This is an attempt to solve the issue:

```
com.fasterxml.jackson.databind.JsonMappingException: Scala module 2.10.3 requires Jackson Databind version >= 2.10.0 and < 2.11.0
```